spring:
  application:
    name: CShop
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    repair-on-migrate: true
    validate-on-migrate: false
    enabled: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO

app:
  signature_key: ${SIGNATURE_KEY}
  secretKey: ${ADMIN_KEY}

server:
  port: 8080

#Для отладки
#spring:
#  application:
#    name: CShop
#  datasource:
#    url: jdbc:postgresql://localhost:5431/clotheDB
#    username: postgres
#    password: 1111
#    driver-class-name: org.postgresql.Driver
#
#  flyway:
#    repair-on-migrate: true
#    validate-on-migrate: false
#    enabled: true
#    locations: classpath:db/migration
#    schemas: public
#    default-schema: public
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#
#logging:
#  level:
#    root: INFO
#
#app:
#  signature_key: ErwbRrF9T4vgdzPAAye6MwTHWiTmJ4Kn21KDIb0SnSjjA5HV9APgilI9CGMGyQQk
#  secretKey: yrF%B$~#IO